environment:
  integrate:
    ulr: "http://146.59.32.4/index.php"
    browser: "CHROME"
    wait: "10"
    existingUSerFirstName: "Arek"
    existingUserLastName: "Sale"
    existingUserEmail: "randommailexisting@mail.com"
    ExistingUserPassword: "RandomPassword1"
    onSalePageTitle: "ON SALE"
    priceDrop: "20"
    productsQuantityRange: "5"
    productCustomizationText: "Testing"
    indexOfProductToSetQuantity: "0"
    quantityToSetInProduct: "5"
    flag: "N"
  test:
    ulr: "http://146.59.32.4/index.php"
    browser: "CHROME"
    wait: "15"
    existingUSerFirstName: "Arek"
    existingUserLastName: "Sale"
    existingUserEmail: "randommailexisting@mail.com"
    ExistingUserPassword: "RandomPassword1"
    FailLoginAlertMessage: "Authentication failed."
    onSalePageTitle: "ON SALE"
    priceDrop: "20"
    productsQuantityRange: "5"
    productCustomizationText: "Testing"
    indexOfProductToSetQuantity: "0"
    quantityToSetInProduct: "5"
    flag: "y"
  stag:
    ulr: "http://146.59.32.4/index.php"
    browser: "FIREFOX"
    wait: "20"
    existingUSerFirstName: "Arek"
    existingUserLastName: "Sale"
    existingUserEmail: "randommailexisting@mail.com"
    ExistingUserPassword: "RandomPassword1"
    FailLoginAlertMessage: "Authentication failed."
    onSalePageTitle: "ON SALE"
    priceDrop: "20"
    productsQuantityRange: "5"
    productCustomizationText: "Testing"
    indexOfProductToSetQuantity: "0"
    quantityToSetInProduct: "5"
    flag: "n"